# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitpower < Formula
  desc "GitPower CLI tool"
  homepage "https://github.com/PunGrumpy/gitpower"
  version "1.3.3"
  license "MIT"

  depends_on "git"
  depends_on :linux

  if Hardware::CPU.intel?
    if Hardware::CPU.is_64_bit?
      url "https://github.com/PunGrumpy/gitpower/releases/download/v1.3.3/gitpower_Linux_x86_64.tar.gz"
      sha256 "c1a8115669fc7415cc6cfda19d5f2f3097b871a4b6396ca3134dcd6130d45284"

      def install
        bin.install "gitpower"
      end
    end
  end
  if Hardware::CPU.arm?
    if Hardware::CPU.is_64_bit?
      url "https://github.com/PunGrumpy/gitpower/releases/download/v1.3.3/gitpower_Linux_aarch64.tar.gz"
      sha256 "88fe33503b083ba5701734557e996027784b06aa61b95c9d57355457ca1a365f"

      def install
        bin.install "gitpower"
      end
    end
  end

  def caveats
    <<~EOS
      🚀 Thanks for installing GitPower!

      For usage information, run:
        gitpower --help
    EOS
  end

  test do
    system "#{bin}/gitpower --version"
  end
end
