# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitpower < Formula
  desc "GitPower CLI tool"
  homepage "https://github.com/PunGrumpy/gitpower"
  version "1.0.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel?
    if Hardware::CPU.is_64_bit?
      url "https://github.com/PunGrumpy/gitpower/releases/download/v1.0.0/gitpower_Linux_x86_64.tar.gz"
      sha256 "aadec489db4bba1ec0298441131d9a2ca924dcbd40b509e5ed1828193a60b328"

      def install
        bin.install "gitpower"
      end
    end
  end
  if Hardware::CPU.arm?
    if Hardware::CPU.is_64_bit?
      url "https://github.com/PunGrumpy/gitpower/releases/download/v1.0.0/gitpower_Linux_aarch64.tar.gz"
      sha256 "e85550e49399e5647e3bd0dc0a2e442bc797040a080cf809013b08fa26e7a215"

      def install
        bin.install "gitpower"
      end
    end
  end

  test do
    system "#{bin}/gitpower --version"
  end
end
