name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 17 * * 1'
  workflow_dispatch:

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

  tap:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Brew tap
        run: brew tap PunGrumpy/formulas

  install_folder:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Brew install from folder
        run: brew install --formula $(pwd)/Formula/*.rb

  install_tap:
    needs: [tap, install_folder]
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: List files
        run: ls Formula | sed 's/\.rb//g' > files.txt
      - name: Brew install from tap
        run: |
          while read tap_file; do
            brew install pungrumpy/formulas/$tap_file
          done < files.txt

  audit:
    needs: install_tap
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Audit Homebrew Formulas
        run: |
          set -e
          for file in Formula/*.rb; do
            formula=$(basename "$file" .rb)
            echo "Auditing $formula"
            brew audit pungrumpy/formulas/$formula || exit 1
          done
      - name: Dummy Commit to Trigger Build
        uses: gautamkrishnar/keepalive-workflow@master
        with:
          committer_username: 'github-actions[bot]'
          committer_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Dummy commit to trigger build'
