name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 17 * * 1'
  workflow_dispatch:

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

  tap:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Brew tap
        run: brew tap PunGrumpy/formulas

  install_folder:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Brew install from folder
        run: |
          for file in Formula/*.rb; do
            formula=$(basename "$file" .rb)
            if grep -q "depends_on :linux" "$file" && [[ "$(uname)" != "Linux" ]]; then
              echo "Skipping $formula (Linux only)"
              continue
            fi
            echo "Installing $formula from folder"
            brew install --formula "$file" || echo "Warning: Failed to install $formula, but continuing..."
          done

  install_tap:
    needs: [tap, install_folder]
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: List and filter files
        run: |
          for file in Formula/*.rb; do
            formula=$(basename "$file" .rb)
            if grep -q "depends_on :linux" "$file" && [[ "$(uname)" != "Linux" ]]; then
              echo "Skipping $formula (Linux only)"
              continue
            fi
            echo "$formula" >> install_files.txt
          done
          if [ ! -f install_files.txt ]; then
            echo "No compatible formulas found"
            touch install_files.txt
          fi
      - name: Brew install from tap
        run: |
          if [ -s install_files.txt ]; then
            while read tap_file; do
              echo "Installing $tap_file from tap"
              brew install pungrumpy/formulas/$tap_file || echo "Warning: Failed to install $tap_file, but continuing..."
            done < install_files.txt
          else
            echo "No formulas to install"
          fi

  audit:
    needs: install_tap
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Audit Homebrew Formulas
        run: |
          set -e
          for file in Formula/*.rb; do
            formula=$(basename "$file" .rb)
            if grep -q "depends_on :linux" "$file" && [[ "$(uname)" != "Linux" ]]; then
              echo "Skipping audit for $formula (Linux only)"
              continue
            fi
            echo "Auditing $formula"
            brew audit pungrumpy/formulas/$formula || exit 1
          done
      - name: Dummy Commit to Trigger Build
        uses: gautamkrishnar/keepalive-workflow@master
        with:
          committer_username: 'github-actions[bot]'
          committer_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Dummy commit to trigger build'
